//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadane relacji modelu EDM

[assembly: EdmRelationshipAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaGry", "Gry", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projekt.Gry), "Wypozyczenia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projekt.Wypozyczenia), true)]
[assembly: EdmRelationshipAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaDoKlient", "Klienci", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projekt.Klienci), "Wypozyczenia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projekt.Wypozyczenia), true)]
[assembly: EdmRelationshipAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaPracownicy", "Pracownicy", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projekt.Pracownicy), "Wypozyczenia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projekt.Wypozyczenia), true)]
[assembly: EdmRelationshipAttribute("Wypozyczalnia_Gier_komputerowychModel", "Relacjapracownicy2", "Pracownicy", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projekt.Pracownicy), "Zwroty", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projekt.Zwroty), true)]
[assembly: EdmRelationshipAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaWypozyczenia", "Wypozyczenia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projekt.Wypozyczenia), "Zwroty", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Projekt.Zwroty), true)]

#endregion

namespace Projekt
{
    #region Konteksty
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    public partial class Wypozyczalnia_Gier_komputerowychEntities : ObjectContext
    {
        #region Konstruktorzy
    
        /// <summary>
        /// Inicjuje nowy obiekt Wypozyczalnia_Gier_komputerowychEntities, używając parametrów połączenia znalezionych w sekcji „Wypozyczalnia_Gier_komputerowychEntities” pliku konfiguracyjnego aplikacji.
        /// </summary>
        public Wypozyczalnia_Gier_komputerowychEntities() : base("name=Wypozyczalnia_Gier_komputerowychEntities", "Wypozyczalnia_Gier_komputerowychEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Zainicjuj nowy obiekt Wypozyczalnia_Gier_komputerowychEntities.
        /// </summary>
        public Wypozyczalnia_Gier_komputerowychEntities(string connectionString) : base(connectionString, "Wypozyczalnia_Gier_komputerowychEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Zainicjuj nowy obiekt Wypozyczalnia_Gier_komputerowychEntities.
        /// </summary>
        public Wypozyczalnia_Gier_komputerowychEntities(EntityConnection connection) : base(connection, "Wypozyczalnia_Gier_komputerowychEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Metody częściowe
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Właściwości elementu ObjectSet
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Gry> Gry
        {
            get
            {
                if ((_Gry == null))
                {
                    _Gry = base.CreateObjectSet<Gry>("Gry");
                }
                return _Gry;
            }
        }
        private ObjectSet<Gry> _Gry;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Klienci> Klienci
        {
            get
            {
                if ((_Klienci == null))
                {
                    _Klienci = base.CreateObjectSet<Klienci>("Klienci");
                }
                return _Klienci;
            }
        }
        private ObjectSet<Klienci> _Klienci;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Pracownicy> Pracownicy
        {
            get
            {
                if ((_Pracownicy == null))
                {
                    _Pracownicy = base.CreateObjectSet<Pracownicy>("Pracownicy");
                }
                return _Pracownicy;
            }
        }
        private ObjectSet<Pracownicy> _Pracownicy;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Wypozyczenia> Wypozyczenia
        {
            get
            {
                if ((_Wypozyczenia == null))
                {
                    _Wypozyczenia = base.CreateObjectSet<Wypozyczenia>("Wypozyczenia");
                }
                return _Wypozyczenia;
            }
        }
        private ObjectSet<Wypozyczenia> _Wypozyczenia;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Zwroty> Zwroty
        {
            get
            {
                if ((_Zwroty == null))
                {
                    _Zwroty = base.CreateObjectSet<Zwroty>("Zwroty");
                }
                return _Zwroty;
            }
        }
        private ObjectSet<Zwroty> _Zwroty;

        #endregion

        #region Metody AddTo
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Gry. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToGry(Gry gry)
        {
            base.AddObject("Gry", gry);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Klienci. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToKlienci(Klienci klienci)
        {
            base.AddObject("Klienci", klienci);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Pracownicy. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToPracownicy(Pracownicy pracownicy)
        {
            base.AddObject("Pracownicy", pracownicy);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Wypozyczenia. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToWypozyczenia(Wypozyczenia wypozyczenia)
        {
            base.AddObject("Wypozyczenia", wypozyczenia);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Zwroty. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToZwroty(Zwroty zwroty)
        {
            base.AddObject("Zwroty", zwroty);
        }

        #endregion

    }

    #endregion

    #region Jednostki
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Wypozyczalnia_Gier_komputerowychModel", Name="Gry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gry : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Gry.
        /// </summary>
        /// <param name="iD_gry">Nieprawidłowa wartość właściwości ID_gry.</param>
        /// <param name="nazwa">Nieprawidłowa wartość właściwości Nazwa.</param>
        /// <param name="kategoria">Nieprawidłowa wartość właściwości Kategoria.</param>
        /// <param name="kategoria_wiekowa">Nieprawidłowa wartość właściwości Kategoria_wiekowa.</param>
        /// <param name="data_wydania">Nieprawidłowa wartość właściwości Data_wydania.</param>
        /// <param name="cena_dzien">Nieprawidłowa wartość właściwości Cena_dzien.</param>
        public static Gry CreateGry(global::System.Int32 iD_gry, global::System.String nazwa, global::System.String kategoria, global::System.String kategoria_wiekowa, global::System.String data_wydania, global::System.Int32 cena_dzien)
        {
            Gry gry = new Gry();
            gry.ID_gry = iD_gry;
            gry.Nazwa = nazwa;
            gry.Kategoria = kategoria;
            gry.Kategoria_wiekowa = kategoria_wiekowa;
            gry.Data_wydania = data_wydania;
            gry.Cena_dzien = cena_dzien;
            return gry;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_gry
        {
            get
            {
                return _ID_gry;
            }
            set
            {
                if (_ID_gry != value)
                {
                    OnID_gryChanging(value);
                    ReportPropertyChanging("ID_gry");
                    _ID_gry = StructuralObject.SetValidValue(value, "ID_gry");
                    ReportPropertyChanged("ID_gry");
                    OnID_gryChanged();
                }
            }
        }
        private global::System.Int32 _ID_gry;
        partial void OnID_gryChanging(global::System.Int32 value);
        partial void OnID_gryChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, false, "Nazwa");
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Kategoria
        {
            get
            {
                return _Kategoria;
            }
            set
            {
                OnKategoriaChanging(value);
                ReportPropertyChanging("Kategoria");
                _Kategoria = StructuralObject.SetValidValue(value, false, "Kategoria");
                ReportPropertyChanged("Kategoria");
                OnKategoriaChanged();
            }
        }
        private global::System.String _Kategoria;
        partial void OnKategoriaChanging(global::System.String value);
        partial void OnKategoriaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Kategoria_wiekowa
        {
            get
            {
                return _Kategoria_wiekowa;
            }
            set
            {
                OnKategoria_wiekowaChanging(value);
                ReportPropertyChanging("Kategoria_wiekowa");
                _Kategoria_wiekowa = StructuralObject.SetValidValue(value, false, "Kategoria_wiekowa");
                ReportPropertyChanged("Kategoria_wiekowa");
                OnKategoria_wiekowaChanged();
            }
        }
        private global::System.String _Kategoria_wiekowa;
        partial void OnKategoria_wiekowaChanging(global::System.String value);
        partial void OnKategoria_wiekowaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Data_wydania
        {
            get
            {
                return _Data_wydania;
            }
            set
            {
                OnData_wydaniaChanging(value);
                ReportPropertyChanging("Data_wydania");
                _Data_wydania = StructuralObject.SetValidValue(value, false, "Data_wydania");
                ReportPropertyChanged("Data_wydania");
                OnData_wydaniaChanged();
            }
        }
        private global::System.String _Data_wydania;
        partial void OnData_wydaniaChanging(global::System.String value);
        partial void OnData_wydaniaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cena_dzien
        {
            get
            {
                return _Cena_dzien;
            }
            set
            {
                OnCena_dzienChanging(value);
                ReportPropertyChanging("Cena_dzien");
                _Cena_dzien = StructuralObject.SetValidValue(value, "Cena_dzien");
                ReportPropertyChanged("Cena_dzien");
                OnCena_dzienChanged();
            }
        }
        private global::System.Int32 _Cena_dzien;
        partial void OnCena_dzienChanging(global::System.Int32 value);
        partial void OnCena_dzienChanged();

        

        #endregion

        #region Właściwości nawigacji

        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaGry", "Wypozyczenia")]
        public EntityCollection<Wypozyczenia> Wypozyczenia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaGry", "Wypozyczenia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaGry", "Wypozyczenia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Wypozyczalnia_Gier_komputerowychModel", Name="Klienci")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Klienci : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Klienci.
        /// </summary>
        /// <param name="iD_klienta">Nieprawidłowa wartość właściwości ID_klienta.</param>
        /// <param name="nazwisko">Nieprawidłowa wartość właściwości Nazwisko.</param>
        /// <param name="imie">Nieprawidłowa wartość właściwości Imie.</param>
        /// <param name="adres">Nieprawidłowa wartość właściwości Adres.</param>
        /// <param name="kod_pocztowy">Nieprawidłowa wartość właściwości Kod_pocztowy.</param>
        /// <param name="data_urodzenia">Nieprawidłowa wartość właściwości Data_urodzenia.</param>
        /// <param name="numer_DO">Nieprawidłowa wartość właściwości Numer_DO.</param>
        public static Klienci CreateKlienci(global::System.Int32 iD_klienta, global::System.String nazwisko, global::System.String imie, global::System.String adres, global::System.String kod_pocztowy, global::System.DateTime data_urodzenia, global::System.String numer_DO)
        {
            Klienci klienci = new Klienci();
            klienci.ID_klienta = iD_klienta;
            klienci.Nazwisko = nazwisko;
            klienci.Imie = imie;
            klienci.Adres = adres;
            klienci.Kod_pocztowy = kod_pocztowy;
            klienci.Data_urodzenia = data_urodzenia;
            klienci.Numer_DO = numer_DO;
            return klienci;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_klienta
        {
            get
            {
                return _ID_klienta;
            }
            set
            {
                if (_ID_klienta != value)
                {
                    OnID_klientaChanging(value);
                    ReportPropertyChanging("ID_klienta");
                    _ID_klienta = StructuralObject.SetValidValue(value, "ID_klienta");
                    ReportPropertyChanged("ID_klienta");
                    OnID_klientaChanged();
                }
            }
        }
        private global::System.Int32 _ID_klienta;
        partial void OnID_klientaChanging(global::System.Int32 value);
        partial void OnID_klientaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nazwisko
        {
            get
            {
                return _Nazwisko;
            }
            set
            {
                OnNazwiskoChanging(value);
                ReportPropertyChanging("Nazwisko");
                _Nazwisko = StructuralObject.SetValidValue(value, false, "Nazwisko");
                ReportPropertyChanged("Nazwisko");
                OnNazwiskoChanged();
            }
        }
        private global::System.String _Nazwisko;
        partial void OnNazwiskoChanging(global::System.String value);
        partial void OnNazwiskoChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Imie
        {
            get
            {
                return _Imie;
            }
            set
            {
                OnImieChanging(value);
                ReportPropertyChanging("Imie");
                _Imie = StructuralObject.SetValidValue(value, false, "Imie");
                ReportPropertyChanged("Imie");
                OnImieChanged();
            }
        }
        private global::System.String _Imie;
        partial void OnImieChanging(global::System.String value);
        partial void OnImieChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adres
        {
            get
            {
                return _Adres;
            }
            set
            {
                OnAdresChanging(value);
                ReportPropertyChanging("Adres");
                _Adres = StructuralObject.SetValidValue(value, false, "Adres");
                ReportPropertyChanged("Adres");
                OnAdresChanged();
            }
        }
        private global::System.String _Adres;
        partial void OnAdresChanging(global::System.String value);
        partial void OnAdresChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Kod_pocztowy
        {
            get
            {
                return _Kod_pocztowy;
            }
            set
            {
                OnKod_pocztowyChanging(value);
                ReportPropertyChanging("Kod_pocztowy");
                _Kod_pocztowy = StructuralObject.SetValidValue(value, false, "Kod_pocztowy");
                ReportPropertyChanged("Kod_pocztowy");
                OnKod_pocztowyChanged();
            }
        }
        private global::System.String _Kod_pocztowy;
        partial void OnKod_pocztowyChanging(global::System.String value);
        partial void OnKod_pocztowyChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data_urodzenia
        {
            get
            {
                return _Data_urodzenia;
            }
            set
            {
                OnData_urodzeniaChanging(value);
                ReportPropertyChanging("Data_urodzenia");
                _Data_urodzenia = StructuralObject.SetValidValue(value, "Data_urodzenia");
                ReportPropertyChanged("Data_urodzenia");
                OnData_urodzeniaChanged();
            }
        }
        private global::System.DateTime _Data_urodzenia;
        partial void OnData_urodzeniaChanging(global::System.DateTime value);
        partial void OnData_urodzeniaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Numer_DO
        {
            get
            {
                return _Numer_DO;
            }
            set
            {
                OnNumer_DOChanging(value);
                ReportPropertyChanging("Numer_DO");
                _Numer_DO = StructuralObject.SetValidValue(value, false, "Numer_DO");
                ReportPropertyChanged("Numer_DO");
                OnNumer_DOChanged();
            }
        }
        private global::System.String _Numer_DO;
        partial void OnNumer_DOChanging(global::System.String value);
        partial void OnNumer_DOChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaDoKlient", "Wypozyczenia")]
        public EntityCollection<Wypozyczenia> Wypozyczenia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaDoKlient", "Wypozyczenia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaDoKlient", "Wypozyczenia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Wypozyczalnia_Gier_komputerowychModel", Name="Pracownicy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pracownicy : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Pracownicy.
        /// </summary>
        /// <param name="iD_pracownika">Nieprawidłowa wartość właściwości ID_pracownika.</param>
        /// <param name="imie">Nieprawidłowa wartość właściwości Imie.</param>
        /// <param name="nazwisko">Nieprawidłowa wartość właściwości Nazwisko.</param>
        /// <param name="data_urodzenia">Nieprawidłowa wartość właściwości Data_urodzenia.</param>
        /// <param name="adres">Nieprawidłowa wartość właściwości Adres.</param>
        /// <param name="stanowisko">Nieprawidłowa wartość właściwości Stanowisko.</param>
        public static Pracownicy CreatePracownicy(global::System.Int32 iD_pracownika, global::System.String imie, global::System.String nazwisko, global::System.DateTime data_urodzenia, global::System.String adres, global::System.String stanowisko)
        {
            Pracownicy pracownicy = new Pracownicy();
            pracownicy.ID_pracownika = iD_pracownika;
            pracownicy.Imie = imie;
            pracownicy.Nazwisko = nazwisko;
            pracownicy.Data_urodzenia = data_urodzenia;
            pracownicy.Adres = adres;
            pracownicy.Stanowisko = stanowisko;
            return pracownicy;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_pracownika
        {
            get
            {
                return _ID_pracownika;
            }
            set
            {
                if (_ID_pracownika != value)
                {
                    OnID_pracownikaChanging(value);
                    ReportPropertyChanging("ID_pracownika");
                    _ID_pracownika = StructuralObject.SetValidValue(value, "ID_pracownika");
                    ReportPropertyChanged("ID_pracownika");
                    OnID_pracownikaChanged();
                }
            }
        }
        private global::System.Int32 _ID_pracownika;
        partial void OnID_pracownikaChanging(global::System.Int32 value);
        partial void OnID_pracownikaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Imie
        {
            get
            {
                return _Imie;
            }
            set
            {
                OnImieChanging(value);
                ReportPropertyChanging("Imie");
                _Imie = StructuralObject.SetValidValue(value, false, "Imie");
                ReportPropertyChanged("Imie");
                OnImieChanged();
            }
        }
        private global::System.String _Imie;
        partial void OnImieChanging(global::System.String value);
        partial void OnImieChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nazwisko
        {
            get
            {
                return _Nazwisko;
            }
            set
            {
                OnNazwiskoChanging(value);
                ReportPropertyChanging("Nazwisko");
                _Nazwisko = StructuralObject.SetValidValue(value, false, "Nazwisko");
                ReportPropertyChanged("Nazwisko");
                OnNazwiskoChanged();
            }
        }
        private global::System.String _Nazwisko;
        partial void OnNazwiskoChanging(global::System.String value);
        partial void OnNazwiskoChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data_urodzenia
        {
            get
            {
                return _Data_urodzenia;
            }
            set
            {
                OnData_urodzeniaChanging(value);
                ReportPropertyChanging("Data_urodzenia");
                _Data_urodzenia = StructuralObject.SetValidValue(value, "Data_urodzenia");
                ReportPropertyChanged("Data_urodzenia");
                OnData_urodzeniaChanged();
            }
        }
        private global::System.DateTime _Data_urodzenia;
        partial void OnData_urodzeniaChanging(global::System.DateTime value);
        partial void OnData_urodzeniaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adres
        {
            get
            {
                return _Adres;
            }
            set
            {
                OnAdresChanging(value);
                ReportPropertyChanging("Adres");
                _Adres = StructuralObject.SetValidValue(value, false, "Adres");
                ReportPropertyChanged("Adres");
                OnAdresChanged();
            }
        }
        private global::System.String _Adres;
        partial void OnAdresChanging(global::System.String value);
        partial void OnAdresChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stanowisko
        {
            get
            {
                return _Stanowisko;
            }
            set
            {
                OnStanowiskoChanging(value);
                ReportPropertyChanging("Stanowisko");
                _Stanowisko = StructuralObject.SetValidValue(value, false, "Stanowisko");
                ReportPropertyChanged("Stanowisko");
                OnStanowiskoChanged();
            }
        }
        private global::System.String _Stanowisko;
        partial void OnStanowiskoChanging(global::System.String value);
        partial void OnStanowiskoChanged();

        

        #endregion

        #region Właściwości nawigacji

        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaPracownicy", "Wypozyczenia")]
        public EntityCollection<Wypozyczenia> Wypozyczenia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaPracownicy", "Wypozyczenia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaPracownicy", "Wypozyczenia", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "Relacjapracownicy2", "Zwroty")]
        public EntityCollection<Zwroty> Zwroty
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Zwroty>("Wypozyczalnia_Gier_komputerowychModel.Relacjapracownicy2", "Zwroty");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Zwroty>("Wypozyczalnia_Gier_komputerowychModel.Relacjapracownicy2", "Zwroty", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Wypozyczalnia_Gier_komputerowychModel", Name="Wypozyczenia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Wypozyczenia : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Wypozyczenia.
        /// </summary>
        /// <param name="iD_wypozyczenia">Nieprawidłowa wartość właściwości ID_wypozyczenia.</param>
        /// <param name="iD_Gry">Nieprawidłowa wartość właściwości ID_Gry.</param>
        /// <param name="iD_pracownika">Nieprawidłowa wartość właściwości ID_pracownika.</param>
        /// <param name="iD_klienta">Nieprawidłowa wartość właściwości ID_klienta.</param>
        /// <param name="data_wypozyczenia">Nieprawidłowa wartość właściwości Data_wypozyczenia.</param>
        public static Wypozyczenia CreateWypozyczenia(global::System.Int32 iD_wypozyczenia, global::System.Int32 iD_Gry, global::System.Int32 iD_pracownika, global::System.Int32 iD_klienta, global::System.DateTime data_wypozyczenia)
        {
            Wypozyczenia wypozyczenia = new Wypozyczenia();
            wypozyczenia.ID_wypozyczenia = iD_wypozyczenia;
            wypozyczenia.ID_Gry = iD_Gry;
            wypozyczenia.ID_pracownika = iD_pracownika;
            wypozyczenia.ID_klienta = iD_klienta;
            wypozyczenia.Data_wypozyczenia = data_wypozyczenia;
            return wypozyczenia;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_wypozyczenia
        {
            get
            {
                return _ID_wypozyczenia;
            }
            set
            {
                if (_ID_wypozyczenia != value)
                {
                    OnID_wypozyczeniaChanging(value);
                    ReportPropertyChanging("ID_wypozyczenia");
                    _ID_wypozyczenia = StructuralObject.SetValidValue(value, "ID_wypozyczenia");
                    ReportPropertyChanged("ID_wypozyczenia");
                    OnID_wypozyczeniaChanged();
                }
            }
        }
        private global::System.Int32 _ID_wypozyczenia;
        partial void OnID_wypozyczeniaChanging(global::System.Int32 value);
        partial void OnID_wypozyczeniaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Gry
        {
            get
            {
                return _ID_Gry;
            }
            set
            {
                OnID_GryChanging(value);
                ReportPropertyChanging("ID_Gry");
                _ID_Gry = StructuralObject.SetValidValue(value, "ID_Gry");
                ReportPropertyChanged("ID_Gry");
                OnID_GryChanged();
            }
        }
        private global::System.Int32 _ID_Gry;
        partial void OnID_GryChanging(global::System.Int32 value);
        partial void OnID_GryChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_pracownika
        {
            get
            {
                return _ID_pracownika;
            }
            set
            {
                OnID_pracownikaChanging(value);
                ReportPropertyChanging("ID_pracownika");
                _ID_pracownika = StructuralObject.SetValidValue(value, "ID_pracownika");
                ReportPropertyChanged("ID_pracownika");
                OnID_pracownikaChanged();
            }
        }
        private global::System.Int32 _ID_pracownika;
        partial void OnID_pracownikaChanging(global::System.Int32 value);
        partial void OnID_pracownikaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_klienta
        {
            get
            {
                return _ID_klienta;
            }
            set
            {
                OnID_klientaChanging(value);
                ReportPropertyChanging("ID_klienta");
                _ID_klienta = StructuralObject.SetValidValue(value, "ID_klienta");
                ReportPropertyChanged("ID_klienta");
                OnID_klientaChanged();
            }
        }
        private global::System.Int32 _ID_klienta;
        partial void OnID_klientaChanging(global::System.Int32 value);
        partial void OnID_klientaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data_wypozyczenia
        {
            get
            {
                return _Data_wypozyczenia;
            }
            set
            {
                OnData_wypozyczeniaChanging(value);
                ReportPropertyChanging("Data_wypozyczenia");
                _Data_wypozyczenia = StructuralObject.SetValidValue(value, "Data_wypozyczenia");
                ReportPropertyChanged("Data_wypozyczenia");
                OnData_wypozyczeniaChanged();
            }
        }
        private global::System.DateTime _Data_wypozyczenia;
        partial void OnData_wypozyczeniaChanging(global::System.DateTime value);
        partial void OnData_wypozyczeniaChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaGry", "Gry")]
        public Gry Gry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gry>("Wypozyczalnia_Gier_komputerowychModel.RelacjaGry", "Gry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gry>("Wypozyczalnia_Gier_komputerowychModel.RelacjaGry", "Gry").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Gry> GryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gry>("Wypozyczalnia_Gier_komputerowychModel.RelacjaGry", "Gry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Gry>("Wypozyczalnia_Gier_komputerowychModel.RelacjaGry", "Gry", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaDoKlient", "Klienci")]
        public Klienci Klienci
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Klienci>("Wypozyczalnia_Gier_komputerowychModel.RelacjaDoKlient", "Klienci").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Klienci>("Wypozyczalnia_Gier_komputerowychModel.RelacjaDoKlient", "Klienci").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Klienci> KlienciReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Klienci>("Wypozyczalnia_Gier_komputerowychModel.RelacjaDoKlient", "Klienci");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Klienci>("Wypozyczalnia_Gier_komputerowychModel.RelacjaDoKlient", "Klienci", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaPracownicy", "Pracownicy")]
        public Pracownicy Pracownicy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pracownicy>("Wypozyczalnia_Gier_komputerowychModel.RelacjaPracownicy", "Pracownicy").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pracownicy>("Wypozyczalnia_Gier_komputerowychModel.RelacjaPracownicy", "Pracownicy").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pracownicy> PracownicyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pracownicy>("Wypozyczalnia_Gier_komputerowychModel.RelacjaPracownicy", "Pracownicy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pracownicy>("Wypozyczalnia_Gier_komputerowychModel.RelacjaPracownicy", "Pracownicy", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaWypozyczenia", "Zwroty")]
        public Zwroty Zwroty
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Zwroty>("Wypozyczalnia_Gier_komputerowychModel.RelacjaWypozyczenia", "Zwroty").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Zwroty>("Wypozyczalnia_Gier_komputerowychModel.RelacjaWypozyczenia", "Zwroty").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Zwroty> ZwrotyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Zwroty>("Wypozyczalnia_Gier_komputerowychModel.RelacjaWypozyczenia", "Zwroty");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Zwroty>("Wypozyczalnia_Gier_komputerowychModel.RelacjaWypozyczenia", "Zwroty", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Wypozyczalnia_Gier_komputerowychModel", Name="Zwroty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Zwroty : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Zwroty.
        /// </summary>
        /// <param name="iD_wypozyczenia">Nieprawidłowa wartość właściwości ID_wypozyczenia.</param>
        /// <param name="iD_pracownika">Nieprawidłowa wartość właściwości ID_pracownika.</param>
        /// <param name="data_zwrotu">Nieprawidłowa wartość właściwości data_zwrotu.</param>
        /// <param name="doplaty">Nieprawidłowa wartość właściwości doplaty.</param>
        public static Zwroty CreateZwroty(global::System.Int32 iD_wypozyczenia, global::System.Int32 iD_pracownika, global::System.DateTime data_zwrotu, global::System.Int32 doplaty)
        {
            Zwroty zwroty = new Zwroty();
            zwroty.ID_wypozyczenia = iD_wypozyczenia;
            zwroty.ID_pracownika = iD_pracownika;
            zwroty.data_zwrotu = data_zwrotu;
            zwroty.doplaty = doplaty;
            return zwroty;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_wypozyczenia
        {
            get
            {
                return _ID_wypozyczenia;
            }
            set
            {
                if (_ID_wypozyczenia != value)
                {
                    OnID_wypozyczeniaChanging(value);
                    ReportPropertyChanging("ID_wypozyczenia");
                    _ID_wypozyczenia = StructuralObject.SetValidValue(value, "ID_wypozyczenia");
                    ReportPropertyChanged("ID_wypozyczenia");
                    OnID_wypozyczeniaChanged();
                }
            }
        }
        private global::System.Int32 _ID_wypozyczenia;
        partial void OnID_wypozyczeniaChanging(global::System.Int32 value);
        partial void OnID_wypozyczeniaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_pracownika
        {
            get
            {
                return _ID_pracownika;
            }
            set
            {
                OnID_pracownikaChanging(value);
                ReportPropertyChanging("ID_pracownika");
                _ID_pracownika = StructuralObject.SetValidValue(value, "ID_pracownika");
                ReportPropertyChanged("ID_pracownika");
                OnID_pracownikaChanged();
            }
        }
        private global::System.Int32 _ID_pracownika;
        partial void OnID_pracownikaChanging(global::System.Int32 value);
        partial void OnID_pracownikaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_zwrotu
        {
            get
            {
                return _data_zwrotu;
            }
            set
            {
                Ondata_zwrotuChanging(value);
                ReportPropertyChanging("data_zwrotu");
                _data_zwrotu = StructuralObject.SetValidValue(value, "data_zwrotu");
                ReportPropertyChanged("data_zwrotu");
                Ondata_zwrotuChanged();
            }
        }
        private global::System.DateTime _data_zwrotu;
        partial void Ondata_zwrotuChanging(global::System.DateTime value);
        partial void Ondata_zwrotuChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 doplaty
        {
            get
            {
                return _doplaty;
            }
            set
            {
                OndoplatyChanging(value);
                ReportPropertyChanging("doplaty");
                _doplaty = StructuralObject.SetValidValue(value, "doplaty");
                ReportPropertyChanged("doplaty");
                OndoplatyChanged();
            }
        }
        private global::System.Int32 _doplaty;
        partial void OndoplatyChanging(global::System.Int32 value);
        partial void OndoplatyChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "Relacjapracownicy2", "Pracownicy")]
        public Pracownicy Pracownicy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pracownicy>("Wypozyczalnia_Gier_komputerowychModel.Relacjapracownicy2", "Pracownicy").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pracownicy>("Wypozyczalnia_Gier_komputerowychModel.Relacjapracownicy2", "Pracownicy").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pracownicy> PracownicyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pracownicy>("Wypozyczalnia_Gier_komputerowychModel.Relacjapracownicy2", "Pracownicy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pracownicy>("Wypozyczalnia_Gier_komputerowychModel.Relacjapracownicy2", "Pracownicy", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Wypozyczalnia_Gier_komputerowychModel", "RelacjaWypozyczenia", "Wypozyczenia")]
        public Wypozyczenia Wypozyczenia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaWypozyczenia", "Wypozyczenia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaWypozyczenia", "Wypozyczenia").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Wypozyczenia> WypozyczeniaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaWypozyczenia", "Wypozyczenia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Wypozyczenia>("Wypozyczalnia_Gier_komputerowychModel.RelacjaWypozyczenia", "Wypozyczenia", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
